### ISSUE TITLE
Broken links in Tutorials and Samples section of the documentation

### ISSUE THREAD

**Issue by gk-per** [dotnet/orleans-docs#32]
Looks like at some point in the past the main branch was named differently, Due to this some of the tutorial documentation links in src/docs/tutorials_and_samples redirect to 404.

In index.md: broken link at line 20 
In overview_helloworld.md: broken link at line 8
In Adventure.md: broken link at line 11

**Comment by gk-per** [comment]
Created PR #33 to resolve this issue for the Tutorials and Samples section

**Comment by Expecho** [comment]
Great, but now maybe we should remove the page https://dotnet.github.io/orleans/docs/implementation/testing.html since it contains exactly the same code but without those modifications. It seems to be a full duplicate.

**Comment by Expecho** [comment]
This issue can be closed it seems?
