### ISSUE TITLE
MathGrains doesn't exist.

### ISSUE THREAD

**Issue by QueenCitySmitty** [dotnet/orleans-docs#7]
Looking at [these docs](https://dotnet.github.io/orleans/docs/tutorials_and_samples/index.html), there's a reference to MathGrains that doesn't contain anything. Can it either be removed, or can there be something written for an idea of what MathGrains should be, and I can write the sample?

**Comment by ReubenBond** [comment]
Apologies for the delay, Matt. Yes, please delete it

**Comment by QueenCitySmitty** [comment]
closed with #9
